### ISSUE TITLE
4GB mem node and OOM kill

### ISSUE THREAD

**Issue by cryptomental** [Someguy123/golos-docker#2]
Hi, I have tried countless times to workaround golosd being killed by OOM. Before the recent fork it was fine. My node is 40GB SSD and 4GB ram. Is it still feasible to run the witness node on such low mem specs server after the upgrade? The node replays correctly, it can handle a few blocks and then is killed by OOM by the docker daemon. Perhaps it is about /dev/shm size or other settings....I would be grateful for any hints on how to make it work properly...

**Comment by Someguy123** [comment]
I'm unsure of the shared memory size for GOLOS, on my own node I use 8GB (same as STEEMs shared memory size). Ever since HF16, memory requirements have gone up.

It's important to resize your `/dev/shm` to the correct size, otherwise the GOLOS node will just crash. I usually recommend making it bigger than required.

Be aware that even if you do make the /dev/shm 8gb, it won't actually use 8gb unless the shared memory file grows to that size - this means you can use SWAP if you're a low ranking witness, however I can't guarantee that'll be without issues such as missed blocks.

You should also be aware during the first sync, or a replay, it will use more RAM than normal. You may be able to reduce the RAM usage by allowing the server to synchronize, then stopping the server and starting it again without a replay to clear the memory leak.

You can check your `/dev/shm` size with the following command:

    df -h /dev/shm

**Comment by cryptomental** [comment]
Thank you a lot for explanations, it seems I must upgrade my node. I am setting the issue as resolved.
